variable "resource_group_name" {
  description = "Name of the existing Azure resource group"
  type        = string
  default     = "res000_0_4e69310cb4464d46"
}

variable "domain_name" {
  description = "Domain name for the application (e.g. cutthecrap.dev.deploy-box.com)"
  type        = string
  default     = "cutthecrap.deploy-box.com"
}

variable "vm_size" {
  description = "Azure VM size"
  type        = string
  default     = "Standard_B2s"
}

variable "admin_username" {
  description = "SSH admin username for the VM"
  type        = string
  default     = "azureuser"
}

variable "ssh_public_key_path" {
  description = "Path to the SSH public key file for VM authentication"
  type        = string
  default     = "~/.ssh/id_rsa.pub"
}

variable "github_repo_url" {
  description = "HTTPS URL of the GitHub repository to clone"
  type        = string
  default     = "https://github.com/kalebwbishop/cutthecrap.git"
}

variable "github_repo_branch" {
  description = "Branch to checkout after cloning"
  type        = string
  default     = "dev"
}

# ---------------------------------------------------------------------------
# Backend environment variables (secrets)
# Provide via terraform.tfvars or -var flags — never commit real values.
# ---------------------------------------------------------------------------

variable "workos_api_key" {
  description = "WorkOS API key"
  type        = string
  sensitive   = true
  default     = ""
}

variable "workos_client_id" {
  description = "WorkOS client ID"
  type        = string
  sensitive   = true
  default     = ""
}

variable "deploy_box_client_id" {
  description = "Deploy Box OAuth2 client ID (base64-encoded)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "deploy_box_client_secret" {
  description = "Deploy Box OAuth2 client secret"
  type        = string
  sensitive   = true
  default     = ""
}

variable "chatgpt_api_base" {
  description = "Base URL for the ChatGPT/Azure Function proxy"
  type        = string
  default     = ""
}

variable "chatgpt_api_key" {
  description = "API key for the ChatGPT/Azure Function proxy (EXPO_PUBLIC_CHATGPT_API_KEY)"
  type        = string
  sensitive   = true
  default     = ""
}

# ---------------------------------------------------------------------------
# TLS certificate paths (generated by renew-cert.ps1 into certs/)
# ---------------------------------------------------------------------------

variable "tls_fullchain_path" {
  description = "Path to fullchain.pem (certificate + intermediates)"
  type        = string
  default     = "../certs/fullchain.pem"
}

variable "tls_privkey_path" {
  description = "Path to privkey.pem (private key)"
  type        = string
  default     = "../certs/privkey.pem"
}
